template: Hello, %s!
defaultName: ${DW_DEFAULT_NAME:-Stranger}

accountSid: AC
accountToken: tkn
accountPhone: +15555551111

logging:
  level: INFO
  loggers:
    me.sevifives: DEBUG

database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/example